### ISSUE TITLE
Could not parse

### ISSUE THREAD

**Issue by adamziaja** [Phype/telnet-iot-honeypot#11]
I fixed:
```
2018-01-22 20:21:32   session.py:22     New Session
Traceback (most recent call last):
  File "/root/telnet-iot-honeypot/honeypot/telnet.py", line 75, in handle
    sess.loop()
  File "/root/telnet-iot-honeypot/honeypot/telnet.py", line 96, in loop
    self.session = Session(self.send_string, self.remote[0])
  File "/root/telnet-iot-honeypot/honeypot/session.py", line 26, in __init__
    self.record      = SessionRecord()
  File "/root/telnet-iot-honeypot/honeypot/sampledb_client.py", line 51, in __init__
    self.back    = get_backend()
  File "/root/telnet-iot-honeypot/honeypot/sampledb_client.py", line 14, in get_backend
    if _BACKEND:
UnboundLocalError: local variable '_BACKEND' referenced before assignment
```
with:
```
~/telnet-iot-honeypot/honeypot/sampledb_client.py

def get_backend():
	try:
		_BACKEND
	except:
		_BACKEND = None
```
but still have problems:
```
adam@megazord:~$ telnet 46.X.X.X 2223
Trying 46.X.X.X...
Connected to 46.X.X.X.
Escape character is '^]'.
Login: test
Password: test

Welcome to EmbyLinux 3.13.0-24-generic
 # w
sh: syntax error near unexpected token ` '
 # sh
sh: syntax error near unexpected token ` '
 # Connection closed by foreign host.
adam@megazord:~$ nc 46.X.X.X 2223
��Login: sert
Password: sdf

Welcome to EmbyLinux 3.13.0-24-generic
 # w
sh: syntax error near unexpected token ` '
 # who
sh: syntax error near unexpected token ` '
 # 
```
```
# python honeypot.py
2018-01-22 20:46:44   telnet.py:57      Socket open on port 2223
2018-01-22 20:47:07   telnet.py:72      Client connected at ('176.X.X.X', 18262)
2018-01-22 20:47:07   session.py:22     New Session
2018-01-22 20:47:07   telnet.py:98      Setting timeout to 15.0 seconds
2018-01-22 20:47:09   session.py:35     Session login: user=test password=test
2018-01-22 20:47:11   session.py:84     Could not parse "w"
2018-01-22 20:47:12   session.py:84     Could not parse "sh"
2018-01-22 20:47:27   telnet.py:130     Connection timed out
2018-01-22 20:47:27   session.py:63     Session End
2018-01-22 21:05:06   telnet.py:72      Client connected at ('176.X.X.X', 49579)
2018-01-22 21:05:06   session.py:22     New Session
2018-01-22 21:05:06   telnet.py:98      Setting timeout to 15.0 seconds
2018-01-22 21:05:09   session.py:35     Session login: user=sert password=sdf
2018-01-22 21:05:10   session.py:84     Could not parse "w"
2018-01-22 21:05:11   session.py:84     Could not parse "who"
2018-01-22 21:05:26   telnet.py:130     Connection timed out
2018-01-22 21:05:26   session.py:63     Session End
```
I use mysql and have data in:
```
mysql> select * from conns;
```
OS:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
BTW, what password is on backend? from config and database:
```
mysql> select * from users;
```
both don't work, there is also `backend_salt` in config, not only `backend_user` and `backend_pass`...

**Comment by timhux123** [comment]
I was also experiencing the same error on a new install (16.0.4 LTS) and the fix above to sampledb_client.py corrected the issue. I'm too also seeing the same "Could not parse..." errors regardless on what I type after the telnet connection is made.

**Comment by w00dbury** [comment]
update session.py
`tree = parse(l)`

to
`tree = run(l)`

**Comment by timhux123** [comment]
Updating session.py with "tree = run(l)" corrected the issue for me. Thanks!

**Comment by jlgallegol** [comment]
HI i´m testing but i have the same error. I updated session.py with "tree = run(l)" but it doesn´t work. It has been tested in Ubuntu 16.04.02 LTS
. Can somebody help me?
urot@urot-VirtualBox:~/TFM/telnet-iot-honeypot$ python honeypot.py
2018-06-13 10:13:38   telnet.py:57      Socket open on port 2223
2018-06-13 10:13:42   telnet.py:72      Client connected at ('127.0.0.1', 53816)
2018-06-13 10:13:42   session.py:22     New Session
Traceback (most recent call last):
  File "/home/urot/TFM/telnet-iot-honeypot/honeypot/telnet.py", line 75, in handle
    sess.loop()
  File "/home/urot/TFM/telnet-iot-honeypot/honeypot/telnet.py", line 96, in loop
    self.session = Session(self.send_string, self.remote[0])
  File "/home/urot/TFM/telnet-iot-honeypot/honeypot/session.py", line 26, in __init__
    self.record      = SessionRecord()
  File "/home/urot/TFM/telnet-iot-honeypot/honeypot/sampledb_client.py", line 51, in __init__
    self.back    = get_backend()
  File "/home/urot/TFM/telnet-iot-honeypot/honeypot/sampledb_client.py", line 14, in get_backend
    if _BACKEND:
UnboundLocalError: local variable '_BACKEND' referenced before assignment

**Comment by Mikescops** [comment]
I agree, it does not work on Ubuntu...
