### ISSUE TITLE
UnboundLocalError: local variable '_BACKEND' referenced before assignment

### ISSUE THREAD

**Issue by feddar** [Phype/telnet-iot-honeypot#14]
Hi, after running "python backend.py" and then "python honeypot.py", if i try "telnet 127.0.0.1 2223" the connection close and on terminal where i run honeypot,py i get this error:

```
Traceback (most recent call last):
  File "/telnet-iot-honeypot-master/honeypot/telnet.py", line 75, in handle
    sess.loop()
  File "/telnet-iot-honeypot-master/honeypot/telnet.py", line 96, in loop
    self.session = Session(self.send_string, self.remote[0])
  File "/telnet-iot-honeypot-master/honeypot/session.py", line 26, in __init__
    self.record      = SessionRecord()
  File "/telnet-iot-honeypot-master/honeypot/sampledb_client.py", line 51, in __init__
    self.back    = get_backend()
  File "/telnet-iot-honeypot-master/honeypot/sampledb_client.py", line 14, in get_backend
    if _BACKEND:
UnboundLocalError: local variable '_BACKEND' referenced before assignment
```

Am I doing something bad?
Thanks

**Comment by feddar** [comment]
I'm sorry. I saw now the issue #11 . Must i delete my issue?

**Comment by feddar** [comment]
Duplicate from #11
