### ISSUE TITLE
Database lockups

### ISSUE THREAD

**Issue by timhux123** [Phype/telnet-iot-honeypot#24]
Starting to notice the following over and over which requires me to shutdown and restart backend.py. Sometimes backend.py stays up for a few minutes before the error is seen and sometimes backend.py stays up for days before the error appears. When the error does appear the connection to the database is cut off and the web interface becomes unresponsive.

Any idea?

<my ip address> - - [08/Aug/2019 00:13:49] "PUT /conns HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe

**Comment by timhux123** [comment]
Also found the following today before the  broken pipe error:
  File "/user1/telnet-iot-honeypot/backend/db.py", line 25, in db_wrapper
    return func(*args, **kwargs)
  File "/user1/telnet-iot-honeypot/backend/clientcontroller.py", line 245, in put_session
    self.session.flush() # to get id
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2451, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2549, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 1120, in _emit_insert_statements
    statement, params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO conns (ip, date, user, pass, connhash, text_combined, asn, backend_user_id, ipblock, country, city, lon, lat, network) VALUES (?, ?, ?, ?, ?                               , ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (u'185.107.80.7', 1565278873, u'user1', u'klv123', '00cc1f053cb3020f1bc7020fc880020f1d29020f5d0f020ffdc3020f079e020fd135020f0162020fab57020f30de02                               0f810a020fc52b020f85cd3d1115d2cd1bcdf561cd38aef5cd11cd4acd3b965e5d06861ad1a6cdcd11cd4af33b965e5d06861ad1a68acd11cd0bcde1cd11cd8bf9953b3df5cd38aef5', '[{"data"                               : " # ", "ts": 0.802, "in": false}, {"data": "\\n", "ts": 0.802, "in": true}, {"data": " # ", "ts": 0.802, "in": false}, {"data": "enable\\n" ... (13043 chara                               cters truncated) ... ctory\\n", "ts": 17.681, "in": false}, {"data": "lizrd: applet not found\\n", "ts": 17.681, "in": false}, {"data": " # ", "ts": 17.681, "                               in": false}]', 43350, 1, None, 'NL', 'Unknown', 0.0, 0.0, None)]
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by timhux123** [comment]
This is pointing to a database problem. I'm closing this ticket and will reopen if needed. I created a new database and have not seen the issue since.

**Comment by Phype** [comment]
This is a problem with (how i use) sqlalchemy. It seems that DB queries sometimes fail or the DB connection stales which causes the whole backend to just lock up entirely. I tried some things like changing the allowed number of connection to DB and adding commit() and close() statements everywhere but it doesn't seem to help much. You can try to use MySQL, but similar issues tend to happen there :/
