### ISSUE TITLE
Error on running backend.py

### ISSUE THREAD

**Issue by wirehack7** [Phype/telnet-iot-honeypot#5]
When I try to run `backend.py` I get:

```
Traceback (most recent call last):
  File "backend.py", line 1, in <module>
    from backend.backend import app
  File "/home/telnet-honeypot/telnet-iot-honeypot/backend/backend.py", line 3, in <module>
    from db import get_db
  File "/home/telnet-honeypot/telnet-iot-honeypot/backend/db.py", line 11, in <module>
    from util.config import config
  File "/home/telnet-honeypot/telnet-iot-honeypot/util/config.py", line 9, in <module>
    config = json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 4 column 2 (char 27)
```

My config:
```
{
        "use_local_db": true,

        //"user": "testuser",
        //"backend": "http://localhost:5000",

        //"sql": "mysql+mysqldb://telhoney:xTAqFLqJ2AxAGDgV@localhost/telhoney",
        "max_db_conn": 1,
        "sql": "sqlite:///IoT.sqlite",
        "sample_dir": "samples",

        "save_samples": true,
        "vt_key": "[..]"
}
```

**Comment by Phype** [comment]
Well your config is no valid JSON actually. You use valid javascript comments, but comments are not allowed in JSON at all, because it is a serialization format, as far as i know. Maybe JSON was not the best choice for a configuration file format.... Long story short: Try removing the comments
